// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1EAR3WiOq-ESfaGKgouKEm9oVI0B3cnM',
    appId: '1:771436871512:web:2c08ae92d056d6be4b2f2d',
    messagingSenderId: '771436871512',
    projectId: 'mindsync-15c12',
    authDomain: 'mindsync-15c12.firebaseapp.com',
    storageBucket: 'mindsync-15c12.firebasestorage.app',
    measurementId: 'G-J0S43LB9J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7GSjBomG_B_u_S3t7NV-PUGkXJK_52I',
    appId: '1:771436871512:android:129bcd76536374244b2f2d',
    messagingSenderId: '771436871512',
    projectId: 'mindsync-15c12',
    storageBucket: 'mindsync-15c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnB_xkaGRLwoxIBuwpGLX2b9RUUVzPrE',
    appId: '1:771436871512:ios:796fb6ffd3d3a3034b2f2d',
    messagingSenderId: '771436871512',
    projectId: 'mindsync-15c12',
    storageBucket: 'mindsync-15c12.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnB_xkaGRLwoxIBuwpGLX2b9RUUVzPrE',
    appId: '1:771436871512:ios:796fb6ffd3d3a3034b2f2d',
    messagingSenderId: '771436871512',
    projectId: 'mindsync-15c12',
    storageBucket: 'mindsync-15c12.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1EAR3WiOq-ESfaGKgouKEm9oVI0B3cnM',
    appId: '1:771436871512:web:3fa2d7c758af1a474b2f2d',
    messagingSenderId: '771436871512',
    projectId: 'mindsync-15c12',
    authDomain: 'mindsync-15c12.firebaseapp.com',
    storageBucket: 'mindsync-15c12.firebasestorage.app',
    measurementId: 'G-99HSV67761',
  );
}
